tee_4_1: tee_4_1.c ../common/error_funcs.c ../common/get_num.c
	gcc -o tee_4_1 tee_4_1.c ../common/error_funcs.c ../common/get_num.c
cp_holes_4_2: cp_holes_4_2.c ../common/error_funcs.c ../common/get_num.c
	gcc -o cp_holes_4_2 cp_holes_4_2.c ../common/error_funcs.c ../common/get_num.c
