seek_append_5_2: seek_append_5_2.c ../common/error_funcs.c ../common/get_num.c
	gcc -o seek_append_5_2 seek_append_5_2.c ../common/error_funcs.c ../common/get_num.c
nonatomic_append_5_3: nonatomic_append_5_3.c ../common/error_funcs.c ../common/get_num.c
	gcc -o nonatomic_append_5_3 nonatomic_append_5_3.c ../common/error_funcs.c ../common/get_num.c